// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgZ0plxCznDCuTaP2PpRPsN2ilvdBu53I',
    appId: '1:417548280417:web:aaeaa5fdef0937bf7b4020',
    messagingSenderId: '417548280417',
    projectId: 't3-register',
    authDomain: 't3-register.firebaseapp.com',
    storageBucket: 't3-register.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXO3EfvMbUfXk1Jnkd-VBN-6o1v37oREA',
    appId: '1:417548280417:android:8c3c37ab7f2ca5cf7b4020',
    messagingSenderId: '417548280417',
    projectId: 't3-register',
    storageBucket: 't3-register.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ0dMWNmByD4gpCyjM5MFEJVmDPjBsbYo',
    appId: '1:417548280417:ios:dc5d4ccea7a549767b4020',
    messagingSenderId: '417548280417',
    projectId: 't3-register',
    storageBucket: 't3-register.firebasestorage.app',
    iosBundleId: 'com.example.forms',
  );
}
