// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_SmyCl4_A14rG5o-IZnT7POeFzG0Ybm0',
    appId: '1:546913144814:web:90220476533c91800808ff',
    messagingSenderId: '546913144814',
    projectId: 'crud-app-fbe09',
    authDomain: 'crud-app-fbe09.firebaseapp.com',
    databaseURL: 'https://crud-app-fbe09-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'crud-app-fbe09.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7IP9xSZgdNQzE8wtyaUaR9CPlrDedvqM',
    appId: '1:546913144814:android:06b4a0613b7fa8b50808ff',
    messagingSenderId: '546913144814',
    projectId: 'crud-app-fbe09',
    databaseURL: 'https://crud-app-fbe09-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'crud-app-fbe09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7reTXhnw_FZigTyCKAyHrgccgNrloyDk',
    appId: '1:546913144814:ios:b9b68a829e8a0bf70808ff',
    messagingSenderId: '546913144814',
    projectId: 'crud-app-fbe09',
    databaseURL: 'https://crud-app-fbe09-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'crud-app-fbe09.firebasestorage.app',
    iosBundleId: 'com.example.firstapp',
  );
}
